[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://noter-app-assist.netlify.app"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[[redirects]]
  from = "/api/*"
  to = "https://utilapi.geeksforgeeks.org/api/:splat"
  status = 200
  force = true
